import time
from selenium import webdriver
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()
driver.get("https://practice.automationtesting.in/")
driver.execute_script("window.scrollBy(0, 600);")
Sel_rub = driver.find_element_by_css_selector(".post-160 h3")
Sel_rub.click()
Reviews = driver.find_element_by_class_name('reviews_tab')
Reviews.click()
driver.execute_script("window.scrollBy(0, 300);")
Star = driver.find_element_by_class_name('star-5')
Star.click()
Review = driver.find_element_by_id('comment')
Review.send_keys("Nice book!")
Name = driver.find_element_by_id('author')
Name.send_keys("Selenium")
Email = driver.find_element_by_id('email')
Email.send_keys("123@123.com")
Submit = driver.find_element_by_class_name('submit')
Submit.click()
driver.quit()